version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: rubicode/docker-apps:server
    container_name: server-odm
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: rubicode/docker-apps:client
    container_name: client-react
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local